# First Example:

In [1]:
import os
os.environ["KMP_DUPLICATE_LIB_OK"] = "TRUE"

import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification, Trainer, TrainingArguments
from torch.utils.data import Dataset

In [2]:
# Install required libraries
!pip install accelerate>=1.1.0
!pip install transformers
!pip install torch

Requirement already satisfied: transformers in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (5.10.2)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from transformers) (1.17.0)
Requirement already satisfied: numpy>=1.17 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from transformers) (2.4.4)
Requirement already satisfied: packaging>=20.0 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from transformers) (2026.2.28)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from transformers) (0.25.1)
Requirement already satisfied: safetensors>=0.4.3 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from transformers) (4.67.3)
Requirement already satisfied: click>=8.4.0 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (8.4.1)
Requirement already satisfied: filelock>=3.10.0 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (3.29.0)
Requirement already satisfied: fsspec>=2023.5.0 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (2026.4.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.5.0)
Requirement already satisfied: httpx<1,>=0.23.0 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.15.0)
Requirement already satisfied: anyio in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.12.1)
Requirement already satisfied: certifi in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2026.1.4)
Requirement already satisfied: httpcore==1.* in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.11)
Requirement already satisfied: h11>=0.16 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Requirement already satisfied: shellingham>=1.3.0 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from typer->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: colorama in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from click>=8.4.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.4.6)
Requirement already satisfied: markdown-it-py>=2.2.0 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from rich>=13.8.0->typer->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from rich>=13.8.0->typer->transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers) (0.1.2)
Requirement already satisfied: torch in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (2.12.0)
Requirement already satisfied: filelock in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from torch) (3.29.0)
Requirement already satisfied: typing-extensions>=4.10.0 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from torch) (4.15.0)
Requirement already satisfied: setuptools<82 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from torch) (81.0.0)
Requirement already satisfied: sympy>=1.13.3 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from torch) (2026.4.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from jinja2->torch) (3.0.2)

In [3]:
import torch
from transformers import (
    AutoTokenizer, 
    AutoModelForSequenceClassification, 
    Trainer, 
    TrainingArguments
)
from torch.utils.data import Dataset

In [4]:
#1. Creating a customized Dataset:

class TextDataset(Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):
        # returning a dict that contains input_ids, attention_mask and labels
        item = {key: val[idx] for key, val in self.encodings.items()}
        item['labels'] = torch.tensor(self.labels[idx])
        return item

    
    def __len__(self):
        return len(self.labels)

In [ ]:
tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased")
model = AutoModelForSequenceClassification.from_pretrained("distilbert-base-uncased", num_labels=2)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

In [5]:
# 2. Loading the tokenizer and the model:

tokenizer = AutoTokenizer.from_pretrained("./model/distilbert_model")
model = AutoModelForSequenceClassification.from_pretrained("./model/distilbert_model", num_labels=2)

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

In [6]:
# 4. Preparing the dataset:

texts = [
"This movie is great!",
"I hate this film",
"Wonderful acting",
"Terrible plot"
]
labels = [1, 0, 1, 0] # 1: mens positive, 2: means negative

In [7]:
# 4. Encoding the data:

encodings = tokenizer(texts, truncation=True, padding=True, return_tensors="pt")

In [8]:
# 5. Creating a customized dataset:

train_dataset = TextDataset(encodings, labels)

In [10]:
!pip install transformers[torch]
import transformers

Requirement already satisfied: transformers[torch] in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (5.9.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from transformers[torch]) (1.17.0)
Requirement already satisfied: numpy>=1.17 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from transformers[torch]) (2.4.4)
Requirement already satisfied: packaging>=20.0 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from transformers[torch]) (26.0)
Requirement already satisfied: pyyaml>=5.1 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from transformers[torch]) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from transformers[torch]) (2026.2.28)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from transformers[torch]) (0.22.2)
Requirement already satisfied: typer in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from transformers[torch]) (0.25.1)
Requirement already satisfied: safetensors>=0.4.3 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from transformers[torch]) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from transformers[torch]) (4.67.3)
Requirement already satisfied: torch>=2.4 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from transformers[torch]) (2.12.0)
Collecting accelerate>=1.1.0 (from transformers[torch])
  Downloading accelerate-1.13.0-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: click>=8.4.0 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers[torch]) (8.4.1)
Requirement already satisfied: filelock>=3.10.0 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers[torch]) (3.29.0)
Requirement already satisfied: fsspec>=2023.5.0 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers[torch]) (2026.4.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers[torch]) (1.5.0)
Requirement already satisfied: httpx<1,>=0.23.0 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers[torch]) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers[torch]) (4.15.0)
Requirement already satisfied: anyio in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers[torch]) (4.12.1)
Requirement already satisfied: certifi in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers[torch]) (2026.1.4)
Requirement already satisfied: httpcore==1.* in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers[torch]) (1.0.9)
Requirement already satisfied: idna in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers[torch]) (3.11)
Requirement already satisfied: h11>=0.16 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers[torch]) (0.16.0)
Requirement already satisfied: shellingham>=1.3.0 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from typer->transformers[torch]) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from typer->transformers[torch]) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from typer->transformers[torch]) (0.0.4)
Requirement already satisfied: psutil in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from accelerate>=1.1.0->transformers[torch]) (7.0.0)
Requirement already satisfied: colorama in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from click>=8.4.0->huggingface-hub<2.0,>=1.5.0->transformers[torch]) (0.4.6)
Requirement already satisfied: markdown-it-py>=2.2.0 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from rich>=13.8.0->typer->transformers[torch]) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from rich>=13.8.0->typer->transformers[torch]) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers[torch]) (0.1.2)
Requirement already satisfied: setuptools<82 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from torch>=2.4->transformers[torch]) (81.0.0)
Requirement already satisfied: sympy>=1.13.3 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from torch>=2.4->transformers[torch]) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from torch>=2.4->transformers[torch]) (3.6.1)
Requirement already satisfied: jinja2 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from torch>=2.4->transformers[torch]) (3.1.6)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from sympy>=1.13.3->torch>=2.4->transformers[torch]) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from jinja2->torch>=2.4->transformers[torch]) (3.0.2)
Downloading accelerate-1.13.0-py3-none-any.whl (383 kB)
Installing collected packages: accelerate
Successfully installed accelerate-1.13.0

In [12]:
!pip install 'accelerate>=1.1.0'

ERROR: Invalid requirement: "'accelerate": Expected package name at the start of dependency specifier
    'accelerate
    ^

In [23]:
# Upgrade all relevant packages
!pip install --upgrade torch transformers accelerate

Requirement already satisfied: torch in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (2.12.0)
Requirement already satisfied: transformers in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (5.9.0)
Collecting transformers
  Downloading transformers-5.10.2-py3-none-any.whl.metadata (33 kB)
Requirement already satisfied: accelerate in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (1.13.0)
Requirement already satisfied: filelock in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from torch) (3.29.0)
Requirement already satisfied: typing-extensions>=4.10.0 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from torch) (4.15.0)
Requirement already satisfied: setuptools<82 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from torch) (81.0.0)
Requirement already satisfied: sympy>=1.13.3 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from torch) (2026.4.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from transformers) (1.17.0)
Requirement already satisfied: numpy>=1.17 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from transformers) (2.4.4)
Requirement already satisfied: packaging>=20.0 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from transformers) (2026.2.28)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from transformers) (0.25.1)
Requirement already satisfied: safetensors>=0.4.3 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from transformers) (4.67.3)
Requirement already satisfied: click>=8.4.0 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (8.4.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.5.0)
Requirement already satisfied: httpx<1,>=0.23.0 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: anyio in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.12.1)
Requirement already satisfied: certifi in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2026.1.4)
Requirement already satisfied: httpcore==1.* in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.11)
Requirement already satisfied: h11>=0.16 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Requirement already satisfied: shellingham>=1.3.0 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from typer->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: psutil in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from accelerate) (7.0.0)
Requirement already satisfied: colorama in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from click>=8.4.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.4.6)
Requirement already satisfied: markdown-it-py>=2.2.0 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from rich>=13.8.0->typer->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from rich>=13.8.0->typer->transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers) (0.1.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from jinja2->torch) (3.0.2)
Downloading transformers-5.10.2-py3-none-any.whl (11.0 MB)
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
    --------------------------------------- 0.3/11.0 MB ? eta -:--:--
    --------------------------------------- 0.3/11.0 MB ? eta -:--:--
    --------------------------------------- 0.3/11.0 MB ? eta -:--:--
    --------------------------------------- 0.3/11.0 MB ? eta -:--:--
    --------------------------------------- 0.3/11.0 MB ? eta -:--:--
    --------------------------------------- 0.3/11.0 MB ? eta -:--:--
    --------------------------------------- 0.3/11.0 MB ? eta -:--:--
    --------------------------------------- 0.3/11.0 MB ? eta -:--:--
    --------------------------------------- 0.3/11.0 MB ? eta -:--:--
    --------------------------------------- 0.3/11.0 MB ? eta -:--:--
    --------------------------------------- 0.3/11.0 MB ? eta -:--:--
    --------------------------------------- 0.3/11.0 MB ? eta -:--:--
    --------------------------------------- 0.3/11.0 MB ? eta -:--:--
    --------------------------------------- 0.3/11.0 MB ? eta -:--:--
    --------------------------------------- 0.3/11.0 MB ? eta -:--:--
    --------------------------------------- 0.3/11.0 MB ? eta -:--:--
    --------------------------------------- 0.3/11.0 MB ? eta -:--:--
    --------------------------------------- 0.3/11.0 MB ? eta -:--:--
    --------------------------------------- 0.3/11.0 MB ? eta -:--:--
    --------------------------------------- 0.3/11.0 MB ? eta -:--:--
    --------------------------------------- 0.3/11.0 MB ? eta -:--:--
    --------------------------------------- 0.3/11.0 MB ? eta -:--:--
   - -------------------------------------- 0.5/11.0 MB 55.7 kB/s eta 0:03:09
   - -------------------------------------- 0.5/11.0 MB 55.7 kB/s eta 0:03:09
   - -------------------------------------- 0.5/11.0 MB 55.7 kB/s eta 0:03:09
   - -------------------------------------- 0.5/11.0 MB 55.7 kB/s eta 0:03:09
   - -------------------------------------- 0.5/11.0 MB 55.7 kB/s eta 0:03:09
   - -------------------------------------- 0.5/11.0 MB 55.7 kB/s eta 0:03:09
   - -------------------------------------- 0.5/11.0 MB 55.7 kB/s eta 0:03:09
   - -------------------------------------- 0.5/11.0 MB 55.7 kB/s eta 0:03:09
   - -------------------------------------- 0.5/11.0 MB 55.7 kB/s eta 0:03:09
   - -------------------------------------- 0.5/11.0 MB 55.7 kB/s eta 0:03:09
   - -------------------------------------- 0.5/11.0 MB 55.7 kB/s eta 0:03:09
   - -------------------------------------- 0.5/11.0 MB 55.7 kB/s eta 0:03:09
   - -------------------------------------- 0.5/11.0 MB 55.7 kB/s eta 0:03:09
   - -------------------------------------- 0.5/11.0 MB 55.7 kB/s eta 0:03:09
   -- ------------------------------------- 0.8/11.0 MB 67.4 kB/s eta 0:02:32
   -- ------------------------------------- 0.8/11.0 MB 67.4 kB/s eta 0:02:32
   -- ------------------------------------- 0.8/11.0 MB 67.4 kB/s eta 0:02:32
   -- ------------------------------------- 0.8/11.0 MB 67.4 kB/s eta 0:02:32
   -- ------------------------------------- 0.8/11.0 MB 67.4 kB/s eta 0:02:32
   -- ------------------------------------- 0.8/11.0 MB 67.4 kB/s eta 0:02:32
   -- ------------------------------------- 0.8/11.0 MB 67.4 kB/s eta 0:02:32
   -- ------------------------------------- 0.8/11.0 MB 67.4 kB/s eta 0:02:32
   -- ------------------------------------- 0.8/11.0 MB 67.4 kB/s eta 0:02:32
   --- ------------------------------------ 1.0/11.0 MB 81.7 kB/s eta 0:02:02
   --- ------------------------------------ 1.0/11.0 MB 81.7 kB/s eta 0:02:02
   --- ------------------------------------ 1.0/11.0 MB 81.7 kB/s eta 0:02:02
   --- ------------------------------------ 1.0/11.0 MB 81.7 kB/s eta 0:02:02
   --- ------------------------------------ 1.0/11.0 MB 81.7 kB/s eta 0:02:02
   --- ------------------------------------ 1.0/11.0 MB 81.7 kB/s eta 0:02:02
   --- ------------------------------------ 1.0/11.0 MB 81.7 kB/s eta 0:02:02
   --- ------------------------------------ 1.0/11.0 MB 81.7 kB/s eta 0:02:02
   --- ------------------------------------ 1.0/11.0 MB 81.7 kB/s eta 0:02:02
   ---- ----------------------------------- 1.3/11.0 MB 90.1 kB/s eta 0:01:48
   ---- ----------------------------------- 1.3/11.0 MB 90.1 kB/s eta 0:01:48
   ---- ----------------------------------- 1.3/11.0 MB 90.1 kB/s eta 0:01:48
   ---- ----------------------------------- 1.3/11.0 MB 90.1 kB/s eta 0:01:48
   ---- ----------------------------------- 1.3/11.0 MB 90.1 kB/s eta 0:01:48
   ---- ----------------------------------- 1.3/11.0 MB 90.1 kB/s eta 0:01:48
   ---- ----------------------------------- 1.3/11.0 MB 90.1 kB/s eta 0:01:48
   ---- ----------------------------------- 1.3/11.0 MB 90.1 kB/s eta 0:01:48
   ---- ----------------------------------- 1.3/11.0 MB 90.1 kB/s eta 0:01:48
   ---- ----------------------------------- 1.3/11.0 MB 90.1 kB/s eta 0:01:48
   ---- ----------------------------------- 1.3/11.0 MB 90.1 kB/s eta 0:01:48
   ---- ----------------------------------- 1.3/11.0 MB 90.1 kB/s eta 0:01:48
   ----- ---------------------------------- 1.6/11.0 MB 91.7 kB/s eta 0:01:43
   ----- ---------------------------------- 1.6/11.0 MB 91.7 kB/s eta 0:01:43
   ----- ---------------------------------- 1.6/11.0 MB 91.7 kB/s eta 0:01:43
   ----- ---------------------------------- 1.6/11.0 MB 91.7 kB/s eta 0:01:43
   ----- ---------------------------------- 1.6/11.0 MB 91.7 kB/s eta 0:01:43
   ----- ---------------------------------- 1.6/11.0 MB 91.7 kB/s eta 0:01:43
   ----- ---------------------------------- 1.6/11.0 MB 91.7 kB/s eta 0:01:43
   ----- ---------------------------------- 1.6/11.0 MB 91.7 kB/s eta 0:01:43
   ----- ---------------------------------- 1.6/11.0 MB 91.7 kB/s eta 0:01:43
   ----- ---------------------------------- 1.6/11.0 MB 91.7 kB/s eta 0:01:43
   ----- ---------------------------------- 1.6/11.0 MB 91.7 kB/s eta 0:01:43
   ----- ---------------------------------- 1.6/11.0 MB 91.7 kB/s eta 0:01:43
   ----- ---------------------------------- 1.6/11.0 MB 91.7 kB/s eta 0:01:43
   ------ --------------------------------- 1.8/11.0 MB 92.4 kB/s eta 0:01:40
   ------ --------------------------------- 1.8/11.0 MB 92.4 kB/s eta 0:01:40
   ------ --------------------------------- 1.8/11.0 MB 92.4 kB/s eta 0:01:40
   ------ --------------------------------- 1.8/11.0 MB 92.4 kB/s eta 0:01:40
   ------ --------------------------------- 1.8/11.0 MB 92.4 kB/s eta 0:01:40
   ------ --------------------------------- 1.8/11.0 MB 92.4 kB/s eta 0:01:40
   ------ --------------------------------- 1.8/11.0 MB 92.4 kB/s eta 0:01:40
   ------ --------------------------------- 1.8/11.0 MB 92.4 kB/s eta 0:01:40
   ------ --------------------------------- 1.8/11.0 MB 92.4 kB/s eta 0:01:40
   ------ --------------------------------- 1.8/11.0 MB 92.4 kB/s eta 0:01:40
   ------ --------------------------------- 1.8/11.0 MB 92.4 kB/s eta 0:01:40
   ------ --------------------------------- 1.8/11.0 MB 92.4 kB/s eta 0:01:40
   ------ --------------------------------- 1.8/11.0 MB 92.4 kB/s eta 0:01:40
   ------- -------------------------------- 2.1/11.0 MB 93.1 kB/s eta 0:01:36
   ------- -------------------------------- 2.1/11.0 MB 93.1 kB/s eta 0:01:36
   ------- -------------------------------- 2.1/11.0 MB 93.1 kB/s eta 0:01:36
   ------- -------------------------------- 2.1/11.0 MB 93.1 kB/s eta 0:01:36
   ------- -------------------------------- 2.1/11.0 MB 93.1 kB/s eta 0:01:36
   ------- -------------------------------- 2.1/11.0 MB 93.1 kB/s eta 0:01:36
   ------- -------------------------------- 2.1/11.0 MB 93.1 kB/s eta 0:01:36
   ------- -------------------------------- 2.1/11.0 MB 93.1 kB/s eta 0:01:36
   ------- -------------------------------- 2.1/11.0 MB 93.1 kB/s eta 0:01:36
   ------- -------------------------------- 2.1/11.0 MB 93.1 kB/s eta 0:01:36
   ------- -------------------------------- 2.1/11.0 MB 93.1 kB/s eta 0:01:36
   ------- -------------------------------- 2.1/11.0 MB 93.1 kB/s eta 0:01:36
   ------- -------------------------------- 2.1/11.0 MB 93.1 kB/s eta 0:01:36
   ------- -------------------------------- 2.1/11.0 MB 93.1 kB/s eta 0:01:36
   -------- ------------------------------- 2.4/11.0 MB 92.4 kB/s eta 0:01:34
   -------- ------------------------------- 2.4/11.0 MB 92.4 kB/s eta 0:01:34
   -------- ------------------------------- 2.4/11.0 MB 92.4 kB/s eta 0:01:34
   -------- ------------------------------- 2.4/11.0 MB 92.4 kB/s eta 0:01:34
   -------- ------------------------------- 2.4/11.0 MB 92.4 kB/s eta 0:01:34
   -------- ------------------------------- 2.4/11.0 MB 92.4 kB/s eta 0:01:34
   -------- ------------------------------- 2.4/11.0 MB 92.4 kB/s eta 0:01:34
   -------- ------------------------------- 2.4/11.0 MB 92.4 kB/s eta 0:01:34
   -------- ------------------------------- 2.4/11.0 MB 92.4 kB/s eta 0:01:34
   -------- ------------------------------- 2.4/11.0 MB 92.4 kB/s eta 0:01:34
   -------- ------------------------------- 2.4/11.0 MB 92.4 kB/s eta 0:01:34
   -------- ------------------------------- 2.4/11.0 MB 92.4 kB/s eta 0:01:34
   --------- ------------------------------ 2.6/11.0 MB 93.5 kB/s eta 0:01:30
   --------- ------------------------------ 2.6/11.0 MB 93.5 kB/s eta 0:01:30
   --------- ------------------------------ 2.6/11.0 MB 93.5 kB/s eta 0:01:30
   --------- ------------------------------ 2.6/11.0 MB 93.5 kB/s eta 0:01:30
   --------- ------------------------------ 2.6/11.0 MB 93.5 kB/s eta 0:01:30
   --------- ------------------------------ 2.6/11.0 MB 93.5 kB/s eta 0:01:30
   --------- ------------------------------ 2.6/11.0 MB 93.5 kB/s eta 0:01:30
   --------- ------------------------------ 2.6/11.0 MB 93.5 kB/s eta 0:01:30
   --------- ------------------------------ 2.6/11.0 MB 93.5 kB/s eta 0:01:30
   --------- ------------------------------ 2.6/11.0 MB 93.5 kB/s eta 0:01:30
   --------- ------------------------------ 2.6/11.0 MB 93.5 kB/s eta 0:01:30
   --------- ------------------------------ 2.6/11.0 MB 93.5 kB/s eta 0:01:30
   --------- ------------------------------ 2.6/11.0 MB 93.5 kB/s eta 0:01:30
   --------- ------------------------------ 2.6/11.0 MB 93.5 kB/s eta 0:01:30
   --------- ------------------------------ 2.6/11.0 MB 93.5 kB/s eta 0:01:30
   ---------- ----------------------------- 2.9/11.0 MB 91.9 kB/s eta 0:01:29
   ---------- ----------------------------- 2.9/11.0 MB 91.9 kB/s eta 0:01:29
   ---------- ----------------------------- 2.9/11.0 MB 91.9 kB/s eta 0:01:29
   ---------- ----------------------------- 2.9/11.0 MB 91.9 kB/s eta 0:01:29
   ---------- ----------------------------- 2.9/11.0 MB 91.9 kB/s eta 0:01:29
   ---------- ----------------------------- 2.9/11.0 MB 91.9 kB/s eta 0:01:29
   ---------- ----------------------------- 2.9/11.0 MB 91.9 kB/s eta 0:01:29
   ---------- ----------------------------- 2.9/11.0 MB 91.9 kB/s eta 0:01:29
   ---------- ----------------------------- 2.9/11.0 MB 91.9 kB/s eta 0:01:29
   ---------- ----------------------------- 2.9/11.0 MB 91.9 kB/s eta 0:01:29
   ---------- ----------------------------- 2.9/11.0 MB 91.9 kB/s eta 0:01:29
   ----------- ---------------------------- 3.1/11.0 MB 100.5 kB/s eta 0:01:19
   ----------- ---------------------------- 3.1/11.0 MB 100.5 kB/s eta 0:01:19
   ----------- ---------------------------- 3.1/11.0 MB 100.5 kB/s eta 0:01:19
   ----------- ---------------------------- 3.1/11.0 MB 100.5 kB/s eta 0:01:19
   ----------- ---------------------------- 3.1/11.0 MB 100.5 kB/s eta 0:01:19
   ----------- ---------------------------- 3.1/11.0 MB 100.5 kB/s eta 0:01:19
   ----------- ---------------------------- 3.1/11.0 MB 100.5 kB/s eta 0:01:19
   ----------- ---------------------------- 3.1/11.0 MB 100.5 kB/s eta 0:01:19
   ----------- ---------------------------- 3.1/11.0 MB 100.5 kB/s eta 0:01:19
   ----------- ---------------------------- 3.1/11.0 MB 100.5 kB/s eta 0:01:19
   ----------- ---------------------------- 3.1/11.0 MB 100.5 kB/s eta 0:01:19
   ----------- ---------------------------- 3.1/11.0 MB 100.5 kB/s eta 0:01:19
   ----------- ---------------------------- 3.1/11.0 MB 100.5 kB/s eta 0:01:19
   ------------ --------------------------- 3.4/11.0 MB 99.8 kB/s eta 0:01:17
   ------------ --------------------------- 3.4/11.0 MB 99.8 kB/s eta 0:01:17
   ------------ --------------------------- 3.4/11.0 MB 99.8 kB/s eta 0:01:17
   ------------ --------------------------- 3.4/11.0 MB 99.8 kB/s eta 0:01:17
   ------------ --------------------------- 3.4/11.0 MB 99.8 kB/s eta 0:01:17
   ------------ --------------------------- 3.4/11.0 MB 99.8 kB/s eta 0:01:17
   ------------ --------------------------- 3.4/11.0 MB 99.8 kB/s eta 0:01:17
   ------------ --------------------------- 3.4/11.0 MB 99.8 kB/s eta 0:01:17
   ------------ --------------------------- 3.4/11.0 MB 99.8 kB/s eta 0:01:17
   ------------ --------------------------- 3.4/11.0 MB 99.8 kB/s eta 0:01:17

In [9]:
# 6. Setting Training Parameters:

training_args = TrainingArguments(
    output_dir="./my_model",
    num_train_epochs=3,
    per_device_train_batch_size=2,
    logging_steps=10,
)

In [10]:
# 7. Start the Training Process:

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset #  Now it passes a valid Dataset object
)

trainer.train()

C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages\torch\utils\data\dataloader.py:752: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=6, training_loss=0.00024039057704309622, metrics={'train_runtime': 7.246, 'train_samples_per_second': 1.656, 'train_steps_per_second': 0.828, 'total_flos': 21732932592.0, 'train_loss': 0.00024039057704309622, 'epoch': 3.0})

In [11]:
# 8. Saving the model:

model.save_pretrained("./my_model")
tokenizer.save_pretrained("./my_model")

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

('./my_model\\tokenizer_config.json', './my_model\\tokenizer.json')

# Second Example:

In [15]:
!pip install datasets

Collecting datasets
  Downloading datasets-5.0.0-py3-none-any.whl.metadata (23 kB)
Requirement already satisfied: filelock in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from datasets) (3.29.0)
Requirement already satisfied: numpy>=1.17 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from datasets) (2.4.4)
Collecting pyarrow>=21.0.0 (from datasets)
  Downloading pyarrow-24.0.0-cp312-cp312-win_amd64.whl.metadata (3.0 kB)
Collecting dill<0.4.2,>=0.3.0 (from datasets)
  Downloading dill-0.4.1-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: pandas in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from datasets) (3.0.2)
Requirement already satisfied: requests>=2.32.2 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from datasets) (2.33.1)
Requirement already satisfied: httpx<1.0.0 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from datasets) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from datasets) (4.67.3)
Collecting xxhash (from datasets)
  Downloading xxhash-3.7.0-cp312-cp312-win_amd64.whl.metadata (13 kB)
Collecting multiprocess<0.70.20 (from datasets)
  Downloading multiprocess-0.70.19-py312-none-any.whl.metadata (7.5 kB)
Requirement already satisfied: fsspec<=2026.4.0,>=2023.1.0 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (2026.4.0)
Requirement already satisfied: huggingface-hub<2.0,>=0.25.0 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from datasets) (1.17.0)
Requirement already satisfied: packaging in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from datasets) (26.0)
Requirement already satisfied: pyyaml>=5.1 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from datasets) (6.0.3)
Collecting aiohttp!=4.0.0a0,!=4.0.0a1 (from fsspec[http]<=2026.4.0,>=2023.1.0->datasets)
  Downloading aiohttp-3.14.1-cp312-cp312-win_amd64.whl.metadata (8.5 kB)
Requirement already satisfied: anyio in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from httpx<1.0.0->datasets) (4.12.1)
Requirement already satisfied: certifi in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from httpx<1.0.0->datasets) (2026.1.4)
Requirement already satisfied: httpcore==1.* in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from httpx<1.0.0->datasets) (3.11)
Requirement already satisfied: h11>=0.16 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: click>=8.4.0 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (8.4.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (1.5.0)
Requirement already satisfied: typer<0.26.0,>=0.20.0 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (0.25.1)
Requirement already satisfied: typing-extensions>=4.1.0 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (4.15.0)
Requirement already satisfied: shellingham>=1.3.0 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from typer<0.26.0,>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from typer<0.26.0,>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from typer<0.26.0,>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets) (0.0.4)
Collecting aiohappyeyeballs>=2.5.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets)
  Downloading aiohappyeyeballs-2.6.2-py3-none-any.whl.metadata (5.9 kB)
Collecting aiosignal>=1.4.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets)
  Downloading aiosignal-1.4.0-py3-none-any.whl.metadata (3.7 kB)
Requirement already satisfied: attrs>=17.3.0 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (26.1.0)
Collecting frozenlist>=1.1.1 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets)
  Downloading frozenlist-1.8.0-cp312-cp312-win_amd64.whl.metadata (21 kB)
Collecting multidict<7.0,>=4.5 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets)
  Downloading multidict-6.7.1-cp312-cp312-win_amd64.whl.metadata (5.5 kB)
Collecting propcache>=0.2.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets)
  Downloading propcache-0.5.2-cp312-cp312-win_amd64.whl.metadata (17 kB)
Collecting yarl<2.0,>=1.17.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets)
  Downloading yarl-1.24.2-cp312-cp312-win_amd64.whl.metadata (97 kB)
Requirement already satisfied: colorama in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from click>=8.4.0->huggingface-hub<2.0,>=0.25.0->datasets) (0.4.6)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from requests>=2.32.2->datasets) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from requests>=2.32.2->datasets) (2.6.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets) (0.1.2)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from pandas->datasets) (2025.3)
Requirement already satisfied: six>=1.5 in C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Downloading datasets-5.0.0-py3-none-any.whl (555 kB)
   ---------------------------------------- 0.0/555.1 kB ? eta -:--:--
   ---------------------------------------- 0.0/555.1 kB ? eta -:--:--
   ---------------------------------------- 0.0/555.1 kB ? eta -:--:--
   ---------------------------------------- 0.0/555.1 kB ? eta -:--:--
   ---------------------------------------- 0.0/555.1 kB ? eta -:--:--
   ---------------------------------------- 0.0/555.1 kB ? eta -:--:--
   ---------------------------------------- 0.0/555.1 kB ? eta -:--:--
   ---------------------------------------- 0.0/555.1 kB ? eta -:--:--
   ---------------------------------------- 0.0/555.1 kB ? eta -:--:--
   ---------------------------------------- 0.0/555.1 kB ? eta -:--:--
   ---------------------------------------- 0.0/555.1 kB ? eta -:--:--
   ---------------------------------------- 0.0/555.1 kB ? eta -:--:--
   ---------------------------------------- 0.0/555.1 kB ? eta -:--:--
   ---------------------------------------- 0.0/555.1 kB ? eta -:--:--
   ---------------------------------------- 0.0/555.1 kB ? eta -:--:--
   ---------------------------------------- 0.0/555.1 kB ? eta -:--:--
   ---------------------------------------- 0.0/555.1 kB ? eta -:--:--
   ---------------------------------------- 0.0/555.1 kB ? eta -:--:--
   ---------------------------------------- 0.0/555.1 kB ? eta -:--:--
   ---------------------------------------- 0.0/555.1 kB ? eta -:--:--
   ---------------------------------------- 0.0/555.1 kB ? eta -:--:--
   ---------------------------------------- 0.0/555.1 kB ? eta -:--:--
   ---------------------------------------- 0.0/555.1 kB ? eta -:--:--
   ---------------------------------------- 0.0/555.1 kB ? eta -:--:--
   ---------------------------------------- 0.0/555.1 kB ? eta -:--:--
   ---------------------------------------- 0.0/555.1 kB ? eta -:--:--
   ---------------------------------------- 0.0/555.1 kB ? eta -:--:--
   ---------------------------------------- 0.0/555.1 kB ? eta -:--:--
   ---------------------------------------- 0.0/555.1 kB ? eta -:--:--
   ---------------------------------------- 0.0/555.1 kB ? eta -:--:--
   ---------------------------------------- 0.0/555.1 kB ? eta -:--:--
   ---------------------------------------- 0.0/555.1 kB ? eta -:--:--
   ---------------------------------------- 0.0/555.1 kB ? eta -:--:--
   ---------------------------------------- 0.0/555.1 kB ? eta -:--:--
   ---------------------------------------- 0.0/555.1 kB ? eta -:--:--
   ---------------------------------------- 0.0/555.1 kB ? eta -:--:--
   ---------------------------------------- 0.0/555.1 kB ? eta -:--:--
   ------------------ --------------------- 262.1/555.1 kB ? eta -:--:--
   ------------------ --------------------- 262.1/555.1 kB ? eta -:--:--
   ------------------ --------------------- 262.1/555.1 kB ? eta -:--:--
   ------------------ --------------------- 262.1/555.1 kB ? eta -:--:--
   ------------------ --------------------- 262.1/555.1 kB ? eta -:--:--
   ------------------ --------------------- 262.1/555.1 kB ? eta -:--:--
   ------------------ --------------------- 262.1/555.1 kB ? eta -:--:--
   ------------------ --------------------- 262.1/555.1 kB ? eta -:--:--
   ------------------ --------------------- 262.1/555.1 kB ? eta -:--:--
   ------------------ --------------------- 262.1/555.1 kB ? eta -:--:--
   ------------------ --------------------- 262.1/555.1 kB ? eta -:--:--
   ------------------ --------------------- 262.1/555.1 kB ? eta -:--:--
   ------------------ --------------------- 262.1/555.1 kB ? eta -:--:--
   ------------------ --------------------- 262.1/555.1 kB ? eta -:--:--
   ------------------ --------------------- 262.1/555.1 kB ? eta -:--:--
   ------------------ --------------------- 262.1/555.1 kB ? eta -:--:--
   ------------------ --------------------- 262.1/555.1 kB ? eta -:--:--
   ------------------ --------------------- 262.1/555.1 kB ? eta -:--:--
   ------------------ --------------------- 262.1/555.1 kB ? eta -:--:--
   ------------------ --------------------- 262.1/555.1 kB ? eta -:--:--
   ------------------ --------------------- 262.1/555.1 kB ? eta -:--:--
   ------------------ --------------------- 262.1/555.1 kB ? eta -:--:--
   ------------------ --------------------- 262.1/555.1 kB ? eta -:--:--
   ------------------ --------------------- 262.1/555.1 kB ? eta -:--:--
   ------------------------------------ -- 524.3/555.1 kB 49.5 kB/s eta 0:00:01
   ------------------------------------ -- 524.3/555.1 kB 49.5 kB/s eta 0:00:01
   ------------------------------------ -- 524.3/555.1 kB 49.5 kB/s eta 0:00:01
   ---------------------------------------- 555.1/555.1 kB 50.0 kB/s  0:00:13
Downloading dill-0.4.1-py3-none-any.whl (120 kB)
Downloading multiprocess-0.70.19-py312-none-any.whl (150 kB)
Downloading aiohttp-3.14.1-cp312-cp312-win_amd64.whl (479 kB)
Downloading multidict-6.7.1-cp312-cp312-win_amd64.whl (46 kB)
Downloading yarl-1.24.2-cp312-cp312-win_amd64.whl (92 kB)
Downloading aiohappyeyeballs-2.6.2-py3-none-any.whl (15 kB)
Downloading aiosignal-1.4.0-py3-none-any.whl (7.5 kB)
Downloading frozenlist-1.8.0-cp312-cp312-win_amd64.whl (44 kB)
Downloading propcache-0.5.2-cp312-cp312-win_amd64.whl (42 kB)
Downloading pyarrow-24.0.0-cp312-cp312-win_amd64.whl (27.4 MB)
   ---------------------------------------- 0.0/27.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.4 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.4 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.4 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.4 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.4 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.4 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.4 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.4 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.4 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.4 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.4 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.4 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.4 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.4 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.4 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.4 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.4 MB ? eta -:--:--
    --------------------------------------- 0.5/27.4 MB 77.7 kB/s eta 0:05:46
    --------------------------------------- 0.5/27.4 MB 77.7 kB/s eta 0:05:46
    --------------------------------------- 0.5/27.4 MB 77.7 kB/s eta 0:05:46
    --------------------------------------- 0.5/27.4 MB 77.7 kB/s eta 0:05:46
    --------------------------------------- 0.5/27.4 MB 77.7 kB/s eta 0:05:46
    --------------------------------------- 0.5/27.4 MB 77.7 kB/s eta 0:05:46
    --------------------------------------- 0.5/27.4 MB 77.7 kB/s eta 0:05:46
    --------------------------------------- 0.5/27.4 MB 77.7 kB/s eta 0:05:46
    --------------------------------------- 0.5/27.4 MB 77.7 kB/s eta 0:05:46
    --------------------------------------- 0.5/27.4 MB 77.7 kB/s eta 0:05:46
    --------------------------------------- 0.5/27.4 MB 77.7 kB/s eta 0:05:46
    --------------------------------------- 0.5/27.4 MB 77.7 kB/s eta 0:05:46
    --------------------------------------- 0.5/27.4 MB 77.7 kB/s eta 0:05:46
   - -------------------------------------- 0.8/27.4 MB 86.9 kB/s eta 0:05:06
   - -------------------------------------- 0.8/27.4 MB 86.9 kB/s eta 0:05:06
   - -------------------------------------- 0.8/27.4 MB 86.9 kB/s eta 0:05:06
   - -------------------------------------- 0.8/27.4 MB 86.9 kB/s eta 0:05:06
   - -------------------------------------- 0.8/27.4 MB 86.9 kB/s eta 0:05:06
   - -------------------------------------- 0.8/27.4 MB 86.9 kB/s eta 0:05:06
   - -------------------------------------- 0.8/27.4 MB 86.9 kB/s eta 0:05:06
   - -------------------------------------- 0.8/27.4 MB 86.9 kB/s eta 0:05:06
   - -------------------------------------- 0.8/27.4 MB 86.9 kB/s eta 0:05:06
   - -------------------------------------- 0.8/27.4 MB 86.9 kB/s eta 0:05:06
   - -------------------------------------- 0.8/27.4 MB 86.9 kB/s eta 0:05:06
   - -------------------------------------- 0.8/27.4 MB 86.9 kB/s eta 0:05:06
   - -------------------------------------- 0.8/27.4 MB 86.9 kB/s eta 0:05:06
   - -------------------------------------- 0.8/27.4 MB 86.9 kB/s eta 0:05:06
   - -------------------------------------- 0.8/27.4 MB 86.9 kB/s eta 0:05:06
   - -------------------------------------- 0.8/27.4 MB 86.9 kB/s eta 0:05:06
   - -------------------------------------- 1.0/27.4 MB 81.8 kB/s eta 0:05:22
   - -------------------------------------- 1.0/27.4 MB 81.8 kB/s eta 0:05:22
   - -------------------------------------- 1.0/27.4 MB 81.8 kB/s eta 0:05:22
   - -------------------------------------- 1.0/27.4 MB 81.8 kB/s eta 0:05:22
   - -------------------------------------- 1.0/27.4 MB 81.8 kB/s eta 0:05:22
   - -------------------------------------- 1.0/27.4 MB 81.8 kB/s eta 0:05:22
   - -------------------------------------- 1.0/27.4 MB 81.8 kB/s eta 0:05:22
   - -------------------------------------- 1.0/27.4 MB 81.8 kB/s eta 0:05:22
   - -------------------------------------- 1.0/27.4 MB 81.8 kB/s eta 0:05:22
   - -------------------------------------- 1.0/27.4 MB 81.8 kB/s eta 0:05:22
   - -------------------------------------- 1.0/27.4 MB 81.8 kB/s eta 0:05:22
   - -------------------------------------- 1.3/27.4 MB 88.4 kB/s eta 0:04:55
   - -------------------------------------- 1.3/27.4 MB 88.4 kB/s eta 0:04:55
   - -------------------------------------- 1.3/27.4 MB 88.4 kB/s eta 0:04:55
   - -------------------------------------- 1.3/27.4 MB 88.4 kB/s eta 0:04:55
   - -------------------------------------- 1.3/27.4 MB 88.4 kB/s eta 0:04:55
   - -------------------------------------- 1.3/27.4 MB 88.4 kB/s eta 0:04:55
   - -------------------------------------- 1.3/27.4 MB 88.4 kB/s eta 0:04:55
   - -------------------------------------- 1.3/27.4 MB 88.4 kB/s eta 0:04:55
   - -------------------------------------- 1.3/27.4 MB 88.4 kB/s eta 0:04:55
   - -------------------------------------- 1.3/27.4 MB 88.4 kB/s eta 0:04:55
   -- ------------------------------------- 1.6/27.4 MB 93.4 kB/s eta 0:04:36
   -- ------------------------------------- 1.6/27.4 MB 93.4 kB/s eta 0:04:36
   -- ------------------------------------- 1.6/27.4 MB 93.4 kB/s eta 0:04:36
   -- ------------------------------------- 1.6/27.4 MB 93.4 kB/s eta 0:04:36
   -- ------------------------------------- 1.6/27.4 MB 93.4 kB/s eta 0:04:36
   -- ------------------------------------- 1.6/27.4 MB 93.4 kB/s eta 0:04:36
   -- ------------------------------------- 1.6/27.4 MB 93.4 kB/s eta 0:04:36
   -- ------------------------------------- 1.6/27.4 MB 93.4 kB/s eta 0:04:36
   -- ------------------------------------- 1.6/27.4 MB 93.4 kB/s eta 0:04:36
   -- ------------------------------------- 1.6/27.4 MB 93.4 kB/s eta 0:04:36
   -- ------------------------------------- 1.6/27.4 MB 93.4 kB/s eta 0:04:36
   -- ------------------------------------- 1.6/27.4 MB 93.4 kB/s eta 0:04:36
   -- ------------------------------------- 1.8/27.4 MB 95.1 kB/s eta 0:04:29
   -- ------------------------------------- 1.8/27.4 MB 95.1 kB/s eta 0:04:29
   -- ------------------------------------- 1.8/27.4 MB 95.1 kB/s eta 0:04:29
   -- ------------------------------------- 1.8/27.4 MB 95.1 kB/s eta 0:04:29
   -- ------------------------------------- 1.8/27.4 MB 95.1 kB/s eta 0:04:29
   -- ------------------------------------- 1.8/27.4 MB 95.1 kB/s eta 0:04:29
   -- ------------------------------------- 1.8/27.4 MB 95.1 kB/s eta 0:04:29
   -- ------------------------------------- 1.8/27.4 MB 95.1 kB/s eta 0:04:29
   -- ------------------------------------- 1.8/27.4 MB 95.1 kB/s eta 0:04:29

In [16]:
from datasets import Dataset
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    Trainer,
    TrainingArguments
)

In [17]:
tokenizer = AutoTokenizer.from_pretrained("./model/distilbert_model")
model = AutoModelForSequenceClassification.from_pretrained("./model/distilbert_model", num_labels=2)

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

In [18]:

data = {
"text": [
"This movie is great!",
"I hate this film",
"Wonderful acting",
"Terrible plot"
],
"label": [1, 0, 1, 0]
}

In [19]:
dataset = Dataset.from_dict(data)

In [21]:
def tokenize_function(examples):
    return tokenizer(examples["text"], truncation=True, padding=True)

In [22]:
tokenized_dataset = dataset.map(tokenize_function, batched=True)

Map:   0%|          | 0/4 [00:00<?, ? examples/s]

In [23]:
training_args = TrainingArguments(
    output_dir="./my_model",
    num_train_epochs=3,
    per_device_train_batch_size=2,
    logging_steps=10,
)

In [24]:
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset, # يعمل مباشرة
    processing_class=tokenizer,
)

trainer.train()

C:\Users\asus--2018\anaconda3\envs\nlp_course_2026\Lib\site-packages\torch\utils\data\dataloader.py:752: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=6, training_loss=0.00024039057704309622, metrics={'train_runtime': 5.6531, 'train_samples_per_second': 2.123, 'train_steps_per_second': 1.061, 'total_flos': 21732932592.0, 'train_loss': 0.00024039057704309622, 'epoch': 3.0})

In [25]:
model.save_pretrained("./my_model")
tokenizer.save_pretrained("./my_model")

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

('./my_model\\tokenizer_config.json', './my_model\\tokenizer.json')